-- CreateTable
CREATE TABLE `Job` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `title` VARCHAR(191) NOT NULL,
    `company` VARCHAR(191) NOT NULL,
    `location` VARCHAR(191) NOT NULL,
    `type` ENUM('fulltime', 'internship') NOT NULL,
    `workSchedule` VARCHAR(255) NULL,
    `workMode` VARCHAR(255) NULL,
    `compensation` TEXT NULL,
    `description` TEXT NOT NULL,
    `overview` TEXT NULL,
    `responsibilities` JSON NULL,
    `minQualifications` JSON NULL,
    `preferredQualifications` JSON NULL,
    `perks` JSON NULL,
    `team` VARCHAR(255) NULL,
    `startingDate` VARCHAR(255) NULL,
    `minDuration` VARCHAR(64) NULL,
    `expectedStipend` VARCHAR(255) NULL,
    `lastDate` VARCHAR(64) NULL,
    `applicationDeadline` VARCHAR(64) NULL,
    `status` ENUM('open', 'expired') NULL,
    `postedDate` VARCHAR(64) NULL,
    `whoCanApply` TEXT NULL,
    `skills` JSON NULL,
    `openings` INTEGER NULL,
    `slug` VARCHAR(191) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `Job_slug_key`(`slug`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
